on: push
jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        include:
          - os: windows
            build: npx caxa --input . --output "courselore--windows--${{ github.sha }}.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/build/server/index.mjs"
            artifact: courselore--windows--${{ github.sha }}.exe
          - os: macos
            build: |
              npx caxa --input . --output "courselore" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/build/server/index.mjs"
              tar czf "courselore--macos--${{ github.sha }}.tgz" "courselore"
            artifact: courselore--macos--${{ github.sha }}.tgz
          - os: ubuntu
            build: |
              npx caxa --input . --output "courselore" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/build/server/index.mjs"
              tar czf "courselore--linux--${{ github.sha }}.tgz" "courselore"
            artifact: courselore--linux--${{ github.sha }}.tgz
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: |
          cd web
          npm ci
          npx shx rm -rf ./server/node_modules/ ./static/node_modules/
          ${{ matrix.build }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: web/${{ matrix.artifact }}

  test:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: |
          cd web
          npm install-ci-test

  publish--npm:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      - run: |
          cd web
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish--release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: courselore--windows--${{ github.sha }}.exe
      - run: mv courselore--windows--${{ github.sha }}.exe courselore--windows--${{ github.ref_name }}.exe
      - uses: actions/download-artifact@v3
        with:
          name: courselore--macos--${{ github.sha }}.tgz
      - run: mv courselore--macos--${{ github.sha }}.tgz courselore--macos--${{ github.ref_name }}.tgz
      - uses: actions/download-artifact@v3
        with:
          name: courselore--linux--${{ github.sha }}.tgz
      - run: mv courselore--linux--${{ github.sha }}.tgz courselore--linux--${{ github.ref_name }}.tgz
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            courselore--windows--${{ github.ref_name }}.exe
            courselore--macos--${{ github.ref_name }}.tgz
            courselore--linux--${{ github.ref_name }}.tgz
