on: push
jobs:
  build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        include:
          - os: windows
            build: npx caxa --input . --output "monitor--windows--${{ github.sha }}.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/build/index.mjs"
            artifact: monitor--windows--${{ github.sha }}.exe
          - os: macos
            build: |
              npx caxa --input . --output "monitor" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/build/index.mjs"
              tar czf "monitor--macos--${{ github.sha }}.tgz" "monitor"
            artifact: monitor--macos--${{ github.sha }}.tgz
          - os: ubuntu
            build: |
              npx caxa --input . --output "monitor" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/build/index.mjs"
              tar czf "monitor--linux--${{ github.sha }}.tgz" "monitor"
            artifact: monitor--linux--${{ github.sha }}.tgz
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: |
          npm ci
          ${{ matrix.build }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

  test:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: |
          npm install-ci-test

  publish--npm:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish--release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: monitor--windows--${{ github.sha }}.exe
      - run: mv monitor--windows--${{ github.sha }}.exe monitor--windows--${{ github.ref_name }}.exe
      - uses: actions/download-artifact@v3
        with:
          name: monitor--macos--${{ github.sha }}.tgz
      - run: mv monitor--macos--${{ github.sha }}.tgz monitor--macos--${{ github.ref_name }}.tgz
      - uses: actions/download-artifact@v3
        with:
          name: monitor--linux--${{ github.sha }}.tgz
      - run: mv monitor--linux--${{ github.sha }}.tgz monitor--linux--${{ github.ref_name }}.tgz
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            monitor--windows--${{ github.ref_name }}.exe
            monitor--macos--${{ github.ref_name }}.tgz
            monitor--linux--${{ github.ref_name }}.tgz
